version: '2'
services:
  frontend:
    build: ./frontend
    ports:
      - '80:80'
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - '8080:8080'
    volumes:
      - /home/dev/Documents/MagDocs/:/home/dev/Documents/MagDocs/
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
